title: "Intro to Semgrep" # a name for your Learning Lab course
tagline: "Learn to set up continuous code scanning with Semgrep." # a short description for your Learning Lab course, displayed on the course catalog
description: "This class will show you how to set up continuous PR scanning with Semgrep, using Juice Shop as an example. You'll also learn to write and roll-out custom Semgrep rules, finding anti-patterns and enforcing secure guardrails unique to *your* company." # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: lab-intro-to-semgrep2    # the name of the repository when it is created for the learner
  repo: lab-intro-to-semgrep   # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
#- type: respond
#  with: 01_first-response.md
- type: createPullRequest # the type of action, full list at https://lab.github.com/docs/actions/
  title: Let's get Semgrep Set Up 
  body: 01_welcome.md
  head: setup-semgrep # branch
#- type: updateBranchProtection

  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
#- title: Assign yourself
#  description: Assign the first issue to yourself.
#  event: issues.assigned
#  link: 'https://github.com/clintgibler/lab-starter/issues/1'
#  actions:
#  - type: gate
#    left: '%payload.pull_request.title%'
#    operator: ===
#    right: Add name to README
#  - type: gate
#    left: '%payload.pull_request.base.ref%'
#    operator: ===
#    right: main
#    else:
#    - type: respond
#      with: 01_try-again.md
#  - type: respond
#    with: 01_nice-work.md

# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: Add Semgrep to CI via a GitHub Action # the title of the step, shown to the learner in the course progress page
  description: We'll add a semgrep.yml  # a description of the step, shown to the learner in the course progress page
  event: issue_comment.created
  link:  '{{ repoUrl }}/pull/1' # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: respond # the type of action, full list at https://lab.github.com/docs/actions
    with: 02_merge_semgrep_yml.md
    data:
      url: '%payload.repository.html_url%/edit/.github/workflows/semgrep.yml?'
      
# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
#- title: Test Semgrep is Working in CI # the title of the step, shown to the learner in the course progress page
#  description: Description 2 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
#- title: Step 3 Title # the title of the step, shown to the learner in the course progress page
#  description: Description 3 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
#- title: Step 4 Title # the title of the step, shown to the learner in the course progress page
#  description: Description 4 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
#- title: Step 5 Title # the title of the step, shown to the learner in the course progress page
#  description: Description 5 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

tags: ["static-analysis", "static-code-analysis", "sast", "devsecops", "semgrep"]